services:
  postgres:
    image: postgres:17-alpine
    container_name: corebank-postgres
    environment:
      POSTGRES_DB: corebank
      POSTGRES_USER: corebank
      POSTGRES_PASSWORD: corebank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U corebank -d corebank"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: corebank-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres-data:
  redis-data: